---
title: "Leaflet"
author: "daisuke ohnuki"
date: "5/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("leaflet")
library(leaflet)
```

```{r}
leaflet() %>% 
    addTiles() %>%
       setView(lng=139.4130,lat=35.4122,zoom=7)
```


```{r}
df <- data.frame(
    id = 1:5,
    lng = rnorm(5,mean=139.4130,sd=0.5),
    lat = rnorm(5,mean=35.4122,sd=0.5),
    pop = c("tokorozawa","shinagawa","yachiyo","odawara","yokohama")
)
knitr::kable(df)
```
```{r}
map1 <- leaflet(df) %>% addTiles()
map1
```
```{r}
map1 %>% 
    addMarkers(lng=~lng,lat=~lat)
```
```{r}
map1%>% 
    addPopups(lng=~lng,lat=~lat,popup=~pop)
```

```{r}
knit_print.htmlwidget <- function (widget, ..., options = NULL) 
{
    file <- basename(tempfile(fileext = ".html"))
    selfcontained <- if(is.null(rmarkdown::metadata$self_contained)) TRUE else rmarkdown::metadata$self_contained
    
    htmlwidgets::saveWidget(widget, file = file, selfcontained = selfcontained)
    content <- if (selfcontained) {
        on.exit(unlink(file), add = TRUE)
        list(srcdoc = paste(readLines(file), collapse = "\n")) 
    }
    else {
        list(src = file)
    }
    
    x <- htmltools::tag("iframe", content)
    
    knitr::knit_print(x, options = options, ...)
}
```

